<?php

namespace AppBundle\Repository;

/**
 * HobbiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbiesRepository extends \Doctrine\ORM\EntityRepository
{
}
